---
- name: CentOS | Add the MariaDB Repo
  template:
    src: templates/centosrepo.j2
    dest: /etc/yum.repos.d/mariadb.repo

- name: CentOS | Install MariaDB
  yum:
    name: "{{ item }}"
    state: "present"
  with_items:
    - "MariaDB-common"
    - "MariaDB-server"
    - "MySQL-python"

- name: CentOS | Start the MariaDB Service
  service: name=mariadb state=started enabled=yes

- name: CentOS | Remove All Anonymous Users
  mysql_user:
    name: ''
    host_all: yes
    state: absent

- name: CentOS | Disable Remote Root Login
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: False

- name: CentOS | Remove the Test Database
  mysql_db: db=test state=absent

- name: CentOS | Set the Root Password for MariaDB
  mysql_user: user=root check_implicit_admin=yes login_password="{{ db_pass }}" password="{{ db_pass }}" host="{{ item }}"
  with_items:
    - "localhost"
    - "127.0.0.1"
    - "::1"

- debug:
    msg: "Database Root password set to '{{ db_pass }}', save this somewhere."

- name: CentOS | Restart the MariaDB Service
  service: name=mariadb state=restarted
...