---
- name: Debian/Ubuntu | Add the MariaDB Repository
  shell: curl -sSL https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | bash -s --
  args:
    warn: False

- name: Debian/Ubuntu | Configure MariaDB Installation
  debconf:
    name: mariadb-server
    question: "{{ item }}"
    vtype: password
    value: "{{ db_pass }}"
  with_items:
    - mysql-server/root_password
    - mysql-server/root_password_again
  register: configure_install
  
- debug:
    msg: "Database Root password set to '{{ db_pass }}', save this somewhere."

- name: Debian/Ubuntu | Install MariaDB with custom configuration
  apt:
    name: mariadb-server
    state: latest
    update_cache: true
  when: configure_install is successful
  register: install_mariadb
...