---
- name: Generate DB Pass
  set_fact:
    db_pass: "{{ lookup('password', '/dev/null chars=ascii_letters length=15') }}"

- include: debian.yml
  when: ansible_os_family|lower == 'debian'

- include: centos.yml
  when: ansible_distribution|lower == 'centos'
...